# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ivarela77 <ivarela77@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/20 18:16:00 by ivarela77         #+#    #+#              #
#    Updated: 2023/12/20 18:19:16 by ivarela77        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC  = src/ft_display_file.c

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	rm -f *.o

flcean:
	rm -f $(NAME)

re:	fclean all